export const CORE_DEFENSE = {
  playerCoreSizePx: 50,
  mobilePlayerCoreSizePx: 46,
  playerShieldSizePx: 68,
  bossControllerScale: 0.88,
  targetLineLimitDesktop: 4,
  targetLineLimitMobile: 2,
  projectileCapDesktop: 18,
  projectileCapMobile: 10,
  baseAttackIntervalMs: 680,
  mobileAttackIntervalMs: 820,
  burstAttackIntervalMult: 0.38,
  burstDurationMs: 1450,
  burstStackMs: 320,
  projectileSpeed: 0.078,
  mobileProjectileSpeed: 0.07,
  projectileDamageMult: 0.62,
  projectilePassiveDamageMult: 0.11,
  projectileCritChance: 0.08,
  projectileCritDamage: 1.85,
};

export const CORE_DEFENSE_HOOKS = {
  projectileFiring: true,
  autoFire: true,
  defenseWaveScaling: false,
  shieldLayers: 1,
  survivalPressure: false,
  multiShot: 0,
  pierce: 0,
  splitShot: false,
  chainLightning: false,
  explosiveShots: false,
  orbitProjectiles: false,
  beamWeapons: false,
  anomalyBullets: false,
};
